dataset:
  _target_: graph_coder.datasets.AstDataset
  _var_: dataset
  root: ~/git-py/raw/python
  batch_size: 8
  collate_fn:
    _var_: collator
  random_seed: 42
  filter_index:
    _target_: graph_coder.config.F.filter_is_processed
