dataset:
  _target_: graph_coder.datasets.AstDataset
  _var_: dataset
  root: ~/git-py/raw/python
  batch_size: 2
  collate_fn:
    _var_: collator
  random_seed: 42
  filter_index:
    - _target_: graph_coder.config.F.filter_is_processed
    - _target_: graph_coder.utils.partial
      func:
        _target_: graph_coder.config.F.filter_max_nodes
        max_nodes: 1000
      _mode_: call
