dataset:
  _target_: graph_coder.datasets.FuncAstDataset
  _var_: dataset
  root: ~/git-py/raw/python
  processed: ~/git-py/func/python
  index_file: func_index.jsonl
  batch_size: 4
  collate_fn:
    _var_: collator
  random_seed: 42
  in_memory: true
  print_summary: true
  filter_index:
    - _target_: graph_coder.config.F.filter_is_processed
    - _target_: graph_coder.config.F.filter_unique_by_column
      column: hash
