dataset:
  _target_: graph_coder.datasets.AstDataset
  _var_: dataset
  root: ~/git-py/raw/python
  batch_size: 2
  collate_fn:
    _var_: collator
  random_seed: 42
  in_memory: true
  print_summary: true
  filter_index:
    - _target_: graph_coder.config.F.filter_is_processed
    - _target_: graph_coder.utils.partial
      func:
        _target_: graph_coder.config.F.filter_max_tokens
        max_tokens: 256
      _mode_: call
    - _target_: graph_coder.utils.partial
      func:
        _target_: graph_coder.config.F.filter_max_lines
        max_lines: 128
      _mode_: call
    - _target_: graph_coder.utils.partial
      func:
        _target_: graph_coder.config.F.filter_max_size
        max_size: 8192
      _mode_: call
