model:
  _target_: graph_coder.models.GraphCoderGenerator
  _var_: model
  vocab_size: 50277
  eos_token_id: 0
  hidden_size: 16
  max_length: 8
  embedding:
    _var_: embedding
  text_encoder:
    _var_: text_encoder
  code_encoder:
    _var_: code_encoder
  graph_encoder:
    _var_: graph_encoder
  decoder:
    _var_: decoder