[tool.poetry]
name = "graph-coder"
version = "0.1.0"
description = ""
authors = ["German Arutyunov <germanarutyunov@gmail.com>"]
readme = "README.md"
packages = [{include = "graph_coder"}]

[[tool.poetry.source]]
name = "torch-cu117"
url = "https://download.pytorch.org/whl/cu117/"
secondary = true

[tool.poetry.dependencies]
python = "^3.9"
catalyst = "^22.4"
astmonkey = {git = "https://github.com/jepler/astmonkey.git", rev = "ast-fixes"}
networkx = "^2.8.8"
aiofiles = "^22.1.0"
pandas = "^1.5.2"
tokenizers = "^0.13.2"
torch = [
    {markers = "sys_platform == 'darwin'", version = "1.13.1"},
    {markers = "sys_platform == 'linux'", source = "torch-cu117", version = "=1.13.1+cu117"},
]
fairseq = "^0.12.2"
performer-pytorch = "^1.1.4"
einops = "^0.6.0"
timm = "^0.6.12"
tensorboard = "^2.11.2"
transformers = "^4.25.1"

[tool.poetry.group.dev.dependencies]
black = {version = "^22.12.0", extras = ["d"]}
pytest = "^7.2.0"
coverage = {version = "^7.0.5", extras = ["toml"]}
mypy = "^0.991"

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'
exclude = 'tests/data'

[tool.coverage.run]
omit = ["tests/*"]

[tool.coverage.html]
directory = "coverage"

[tool.mypy]
files = "graph_coder"
mypy_path = "graph_coder"
python_version = "3.9"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
