decoder:
  _target_: graph_coder.modules.TransformerDecoderPipe
  _var_: decoder
  decoder_layer:
    _target_: torch.nn.TransformerDecoderLayer
    d_model: 256
    nhead: 64
    dim_feedforward: 1024
    dropout: 0.1
    activation: relu
  num_layers: 32