decoder:
  _target_: torch.nn.TransformerDecoder
  _var_: decoder
  decoder_layer:
    _target_: torch.nn.TransformerDecoderLayer
    d_model: 32
    nhead: 4
    dim_feedforward: 64
    dropout: 0.1
    activation: relu
  num_layers: 2