encoder:
  _target_: torch.nn.TransformerEncoder
  _var_: encoder
  encoder_layer:
    _target_: torch.nn.TransformerEncoderLayer
    d_model: 64
    nhead: 4
    dim_feedforward: 128
    dropout: 0.1
    activation: relu
  num_layers: 6