graph_encoder:
  _target_: graph_coder.modules.TokenGTEncoder
  _var_: graph_encoder
  embedding:
    _var_: embedding
  lap_node_id: true
  type_id: true
  encoder_embed_dim: 16
  encoder_ffn_embed_dim: 32
  causal: true
  encoder_layers: 2
  encoder_attention_heads: 4
  performer: true
  attention_dropout: 0
  apply_graphormer_init: true