runner:
  _target_: graph_coder.runners.HumanEvalRunner
  model:
    _var_: _model
  tokenizer:
    _var_: tokenizer
  log_path:
    _var_: log_path
  problem_file: ~/human-eval/HumanEval.jsonl.gz
  temperature: 0.75
  repetition_penalty: 1.3
  top_p: 0.95
  top_k: 1000
  num_samples: 1000
  eos_token_id: 0
  vocab_size: 50277
  print_summary: false
  detect_anomaly: false
  device:
    _var_: device
