model:
  _target_: graph_coder.models.GraphCoderGenerator
  _var_: model
  vocab_size: 50277
  eos_token_id: 1
  hidden_size: 64
  embedding:
    _var_: embedding
  encoder:
    _var_: encoder
  graph_encoder:
    _var_: graph_encoder
  decoder:
    _var_: decoder