collator:
  _target_: graph_coder.utils.partial
  _var_: collator
  func:
    _target_: graph_coder.data.collate_ast
  max_length: 16
  max_seq_length: 2048
  tokenizer:
    _var_: tokenizer
  device:
    _var_: device
  dtype:
    _target_: graph_coder.config.F.get_dtype
    _var_: dtype
    name: float
    _mode_: call
  _mode_: call