_model:
  _target_: graph_coder.models.GraphCoderGeneratorPipe
  _var_: _model
  vocab_size: 50277
  eos_token_id: 0
  hidden_size: 64
  max_length: 4
  embedding:
    _var_: embedding
  text_encoder:
    _var_: text_encoder
  code_encoder:
    _var_: code_encoder
  graph_encoder:
    _var_: graph_encoder
  decoder:
    _var_: decoder

model:
  _target_: deepspeed.pipe.PipelineModule
  _var_: model
  layers:
    _var_: _model.to_layers
  loss_fn:
    _var_: criterion
  num_stages: 2
