collator:
  _target_: graph_coder.data.collate_ast
  _var_: collator
  max_length: 4
  max_seq_length: 256
  tokenizer:
    _var_: tokenizer
  dtype:
    _target_: graph_coder.config.F.get_dtype
    _var_: dtype
    name: float
    _mode_: call
  graph_dtype:
    _target_: graph_coder.config.F.get_dtype
    _var_: graph_dtype
    name: long
    _mode_: call
