runner:
  _target_: graph_coder.runners.GraphCoderGeneratorRunner
  model:
    _var_: model
  eos_token_id: 1
  vocab_size: 50277
  device:
    _target_: catalyst.utils.get_device
    _var_: device
    _mode_: call
