code_encoder:
  _target_: graph_coder.modules.TransformerEncoderPipe
  _var_: code_encoder
  encoder_layer:
    _target_: torch.nn.TransformerEncoderLayer
    d_model: 16
    nhead: 4
    dim_feedforward: 128
    dropout: 0.1
    activation: relu
  num_layers: 2