graph_encoder:
  _target_: graph_coder.modules.TokenGTEncoderPipe
  _var_: graph_encoder
  embedding:
    _var_: token_embedding
  lap_node_id: true
  type_id: true
  encoder_embed_dim: 16
  encoder_ffn_embed_dim: 128
  encoder_layers: 2
  encoder_attention_heads: 4
  attention_dropout: 0.1
  apply_graphormer_init: true