decoder:
  _target_: graph_coder.modules.TransformerDecoderPipe
  _var_: decoder
  decoder_layer:
    _target_: torch.nn.TransformerDecoderLayer
    d_model: 64
    nhead: 16
    dim_feedforward: 512
    dropout: 0.1
    activation: relu
  num_layers: 2