_model:
  _target_: graph_coder.models.GraphCoderGeneratorPipe
  _var_: _model
  vocab_size: 50277
  eos_token_id: 0
  hidden_size: 64
  max_length: 4
  embedding:
    _var_: embedding
  decoder:
    _var_: decoder
  layers:
    - _target_: graph_coder.models.GraphLayerPipe
      encoder:
        _var_: graph_encoder
      has_docstring: false

model:
  _target_: deepspeed.pipe.PipelineModule
  _var_: model
  layers:
    _var_: _model.to_layers
  loss_fn:
    _var_: criterion
  num_stages: 4
