decoder:
  _target_: torch.nn.TransformerDecoder
  _var_: decoder
  decoder_layer:
    _target_: torch.nn.TransformerDecoderLayer
    d_model: 8
    nhead: 2
    dim_feedforward: 16
    dropout: 0.1
    activation: relu
  num_layers: 1