text_encoder:
  _target_: torch.nn.TransformerEncoder
  _var_: text_encoder
  encoder_layer:
    _target_: torch.nn.TransformerEncoderLayer
    d_model: 8
    nhead: 2
    dim_feedforward: 16
    dropout: 0.1
    activation: relu
  num_layers: 1