run:
  - _call_: train
    logdir: logs
    num_epochs: 10
    valid_loader: valid
    valid_metric: loss
    minimize_valid_metric: true
    verbose: true
    timeit: true

    criterion:
      _var_: criterion

    engine:
      _var_: engine

    loaders:
      _target_: graph_coder.config.F.get_keys
      obj:
        _var_: dataset.loaders
      keys:
        - train
        - valid
      _mode_: call

    loggers:
      _var_: loggers

    callbacks:
      - _target_: catalyst.callbacks.checkpoint.CheckpointCallback
        topk: 2
        logdir: logs
        loader_key: &loader_key valid
        metric_key: &metric_key loss
        minimize: &minimize true
      - _target_: catalyst.callbacks.misc.EarlyStoppingCallback
        patience: 20
        loader_key: *loader_key
        metric_key: *metric_key
        minimize: *minimize

