run:
  - _call_: train
    logdir: logs
    num_epochs: 100
    valid_loader: valid
    valid_metric: loss
    minimize_valid_metric: true
    verbose: true
    timeit: true

    criterion:
      _var_: criterion

    engine:
      _var_: engine

    loaders:
      _var_: dataset.loaders

    callbacks:
      - _target_: catalyst.callbacks.checkpoint.CheckpointCallback
        topk: 2
        logdir: logs
        loader_key: &loader_key valid
        metric_key: &metric_key loss
        minimize: &minimize true
      - _target_: catalyst.callbacks.misc.EarlyStoppingCallback
        patience: 20
        loader_key: *loader_key
        metric_key: *metric_key
        minimize: *minimize
      - _target_: catalyst.callbacks.profiler.ProfilerCallback
        epoch: 1
        num_batches: 100
        profiler_kwargs:
          profile_memory: true
          with_stack: true
          with_flops: true
          activities:
            - _target_: graph_coder.config.F.get_activity
              idx: 0 # CPU
              _mode_: call
            - _target_: graph_coder.config.F.get_activity
              idx: 1 # CUDA
              _mode_: call
        tensorboard_path: logs/profiler
        export_chrome_trace_path: logs/profiler/chrome_trace.json
        export_stacks_kwargs:
          path: logs/profiler/stacks.txt
          metric: self_cuda_memory_usage

