collator:
  _target_: graph_coder.data.collate_ast
  _var_: collator
  max_length: 4
  max_seq_length: 256
  use_dict: false
  tokenizer:
    _var_: tokenizer
  has_docstring: False
  has_source: False
