model:
  _target_: graph_coder.models.GraphCoderGenerator
  _var_: model
  vocab_size: 50277
  eos_token_id: 0
  hidden_size: 64
  max_length: 4
  embedding:
    _var_: embedding
  decoder:
    _var_: decoder
  layers:
    - _target_: graph_coder.models.GraphLayer
      encoder:
        _var_: graph_encoder
      has_docstring: false
