name: Build LaTeX document

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-?**'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v2
        with:
          packages: >-
            scheme-basic
            acmart
      - name: pdflatex paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: paper.tex
          working_directory: research
      - name: bibtex paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: paper.aux
          compiler: bibtex
          working_directory: research
      - name: pdflatex paper
        uses: xu-cheng/latex-action@v2
        with:
          root_file: paper.tex
          working_directory: research
      - name: Upload PDF file
        uses: ncipollo/release-action@v1
        with:
          artifacts: "research/paper.pdf"
          bodyFile: "research/body.md"
